#! /usr/bin/env python3

import subprocess
import sys
import time

def main():
    keyfile = sys.argv[-1]
    username = sys.argv[-3]
    dns_server = "proj4-dns.5700.network"
    dns_related_files = ["dnsserver", "deploy_geoip_database"]
    replica_related_files = ["httpserver", "pageviews.csv"]
    replicas = ["proj4-repl1.5700.network", "proj4-repl2.5700.network", "proj4-repl3.5700.network",
                "proj4-repl4.5700.network", "proj4-repl5.5700.network",
                "proj4-repl6.5700.network", "proj4-repl7.5700.network"]

    for each in dns_related_files:
        # subprocess.check_output("scp -i " + keyfile + " "+ each + " yexuran@" + dns_server + ":/home/yexuran", shell=True)
        subprocess.check_output("scp -i " + keyfile + " "+ each + " " + username + "@" + dns_server + ":/home/yexuran; exit 0", stderr=subprocess.STDOUT, shell=True)
    
    ssh_perm = "ssh -i " + keyfile + " " + username + "@" + dns_server + " 'chmod a+x ~/dnsserver'; exit 0"
    subprocess.call(ssh_perm, stderr=subprocess.STDOUT, shell=True)
    # run deploy_database.py to pre-deploy database
    # subprocess.check_output("ssh -i " + keyfile +" " + "yexuran@" + dns_server +" '"+"DISPLAY=:0 ./deploy_geoip_database &"+"'", shell=True)
    subprocess.check_output("ssh -i " + keyfile +" " + username + "@" + dns_server +" '"+"DISPLAY=:0 ./deploy_geoip_database &"+"'; exit 0", stderr=subprocess.STDOUT, shell=True)


    # change mod
    for replica in replicas:
        for each in replica_related_files:
            # subprocess.check_output("scp -i " + keyfile + " " + each + " yexuran@" + replica + ":/home/yexuran", shell=True)
            subprocess.check_output("scp -i " + keyfile + " " + each + " " +username + "@" + replica + ":/home/yexuran; exit 0", stderr=subprocess.STDOUT, shell=True)
        # ssh_perm = "ssh -i " + keyfile + " " + "yexuran@" + replica + " 'chmod a+x ~/httpserver'"
        ssh_perm = "ssh -i " + keyfile + " " + username + "@" + replica + " 'chmod a+x ~/httpserver'; exit 0"
        subprocess.call(ssh_perm, stderr=subprocess.STDOUT, shell=True)
        # subprocess.check_output("scp -i " + keyfile + " " + "-r ./file" + " yexuran@" + replica + ":/home/yexuran", shell=True)
        subprocess.check_output("scp -i " + keyfile + " " + "-r ./file" + " " + username + "@" + replica + ":/home/yexuran; exit 0", stderr=subprocess.STDOUT, shell=True)


if __name__ == '__main__':
    main()
    sys.exit(0)
