#!/bin/bash

DNSHOST=proj4-dns.5700.network
HTTPHOSTS=("proj4-repl1.5700.network"
           "proj4-repl2.5700.network"
           "proj4-repl3.5700.network"
           "proj4-repl4.5700.network"
           "proj4-repl5.5700.network"
           "proj4-repl6.5700.network"
           "proj4-repl7.5700.network")
DIR=

PORT=""
ORIGIN=""
NAME=""
USERNAME=""
KEYFILE=""

while [ $# -gt 0 ]
do
    case $1 in
        --port | -p)
            shift; PORT=$1;;
        --origin | -o)
            shift; ORIGIN=$1;;
        --name | -n)
            shift; NAME=$1;;
        --username | -u)
            shift; USERNAME=$1;;
        --identity | -i)
            shift; KEYFILE=$1;;
        *)
            usage;;
    esac
    shift
done



pid=`ssh -i $KEYFILE $USERNAME@$DNSHOST "ps -aux | grep $USERNAME.*dnsserver | grep -v grep" | head -1`
ssh -i $KEYFILE $USERNAME@$DNSHOST "kill -9 $pid && ps -aux | grep $USERNAME.*dnsserver"
echo ''


for host in ${HTTPHOSTS[@]};
do
    pid=`ssh -i $KEYFILE $USERNAME@$host "ps -aux | grep $USERNAME.*httpserver | grep -v grep" | head -1`
    ssh -i $KEYFILE $USERNAME@$host "kill -9 $pid && ps -aux | grep $USERNAME.*httpserver"
    echo ''
done
exit 0